apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
spec:
  host: hostname
  path: /api
  tls:
    termination: edge
  to:
    kind: Service
    name: backend
    weight: 100
  wildcardPolicy: None