apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  host: host.name
  path: /api
  tls:
    termination: edge
  to:
    kind: Service
    name: backend
    weight: 100
  wildcardPolicy: None